DROP TABLE IF EXISTS arts CASCADE;

CREATE TABLE arts (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  image TEXT NOT NULL,
  time_stamp TIMESTAMP NOT NULL DEFAULT NOW(),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
