DROP TABLE IF EXISTS chats CASCADE;

CREATE TABLE chats (
  id SERIAL PRIMARY KEY NOT NULL,
  body TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  time_stamp TIMESTAMP NOT NULL DEFAULT NOW()
);
