DROP TABLE IF EXISTS forum_comments CASCADE;

CREATE TABLE forum_comments (
  id SERIAL PRIMARY KEY NOT NULL,
  body VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  time_stamp TIMESTAMP NOT NULL DEFAULT NOW(),
  forum_id INTEGER REFERENCES forums(id) ON DELETE CASCADE
);